name: contenta
recipe: drupal8
config:
  php: '7.4'
  composer_version: '2.0.7'
  webroot: web
  drush: ^8
  database: mysql:5.7
  xdebug: true
services:
  appserver:
    build:
      - composer install
